#ifndef CSPLENDOR_ACTION_ENCODER_COMMON_H
#define CSPLENDOR_ACTION_ENCODER_COMMON_H

#include "action.h"
#include "game.h"
#include "rule_query.h"
#include <array>
#include <cstdint>

namespace action_encoder_detail {

struct ReturnCodec {
  static constexpr int H[7][6] = {
      {1, 0, 0, 0, 0, 0},     {1, 1, 1, 1, 1, 1},
      {1, 2, 3, 4, 5, 6},     {1, 3, 6, 10, 15, 21},
      {1, 4, 10, 20, 35, 56}, {1, 5, 15, 35, 70, 126},
      {1, 6, 21, 56, 126, 252},
  };
  static constexpr int OFFSET[4] = {0, 1, 7, 28};

  // Hot path; defined below from a table generated by encode_reference().
  static constexpr int encode(const std::array<uint8_t, 6> &ret);

  static constexpr int encode_reference(const std::array<uint8_t, 6> &ret) {
    int sum = 0;
    for (int i = 0; i < 6; ++i)
      sum += ret[i];
    if (sum == 0)
      return 0;
    if (sum > 3)
      return -1;

    int rank = 0;
    int remaining = sum;
    for (int i = 0; i < 5; ++i) {
      for (int value = remaining; value > static_cast<int>(ret[i]); --value)
        rank += H[5 - i][remaining - value];
      remaining -= ret[i];
    }
    return OFFSET[sum] + rank;
  }

  static constexpr std::array<uint8_t, 6> decode(int pattern) {
    std::array<uint8_t, 6> ret = {0, 0, 0, 0, 0, 0};
    if (pattern < 0 || pattern >= 84)
      return ret;

    int sum = 0;
    while (sum < 3 && pattern >= OFFSET[sum + 1])
      ++sum;

    int rank = pattern - OFFSET[sum];
    int remaining = sum;
    for (int i = 0; i < 5; ++i) {
      for (int value = remaining; value >= 0; --value) {
        const int count = H[5 - i][remaining - value];
        if (rank < count) {
          ret[i] = static_cast<uint8_t>(value);
          remaining -= value;
          break;
        }
        rank -= count;
      }
    }
    ret[5] = static_cast<uint8_t>(remaining);
    return ret;
  }
};

// Rank of every return vector whose six counts are each at most 3, keyed by
// two bits per colour.  Larger counts always exceed the three-token limit.
constexpr std::array<int8_t, 4096> make_return_pattern_by_key() {
  std::array<int8_t, 4096> table{};
  for (unsigned key = 0; key < 4096; ++key) {
    std::array<uint8_t, 6> ret = {0, 0, 0, 0, 0, 0};
    for (int color = 0; color < 6; ++color)
      ret[color] = static_cast<uint8_t>((key >> (2 * color)) & 3U);
    table[key] = static_cast<int8_t>(ReturnCodec::encode_reference(ret));
  }
  return table;
}

inline constexpr std::array<int8_t, 4096> RETURN_PATTERN_BY_KEY =
    make_return_pattern_by_key();

constexpr int ReturnCodec::encode(const std::array<uint8_t, 6> &ret) {
  unsigned key = 0;
  for (int color = 0; color < 6; ++color) {
    if (ret[color] > 3)
      return -1;
    key |= static_cast<unsigned>(ret[color]) << (2 * color);
  }
  return RETURN_PATTERN_BY_KEY[key];
}

constexpr bool return_codec_matches_reference() {
  // Counts 0..4 per colour reach both the table and the over-limit branch.
  std::array<uint8_t, 6> ret = {0, 0, 0, 0, 0, 0};
  for (int code = 0; code < 15625; ++code) {
    int rest = code;
    for (int color = 0; color < 6; ++color) {
      ret[color] = static_cast<uint8_t>(rest % 5);
      rest /= 5;
    }
    if (ReturnCodec::encode(ret) != ReturnCodec::encode_reference(ret))
      return false;
  }
  return true;
}

static_assert(return_codec_matches_reference(),
              "table-driven return codec must match the reference ranking");

inline constexpr std::array<std::array<uint8_t, 3>, 10>
    TAKE_DIFFERENT_COMBINATIONS = {{
        {0, 1, 2}, {0, 1, 3}, {0, 1, 4}, {0, 2, 3}, {0, 2, 4},
        {0, 3, 4}, {1, 2, 3}, {1, 2, 4}, {1, 3, 4}, {2, 3, 4},
    }};

// Reference rank of a take-different action: the original search, kept as
// the oracle from which the hot-path mask table is derived.
constexpr int take_different_index_reference(const std::array<uint8_t, 5> &take) {
  std::array<uint8_t, 3> colors = {0, 0, 0};
  int count = 0;
  for (int color = 0; color < 5; ++color) {
    if (take[color] == 0)
      continue;
    if (take[color] != 1 || count == 3)
      return -1;
    colors[count++] = static_cast<uint8_t>(color);
  }
  if (count == 0)
    return -1;

  if (count == 3) {
    for (int index = 0; index < 10; ++index) {
      const auto &combination = TAKE_DIFFERENT_COMBINATIONS[index];
      if (combination[0] == colors[0] && combination[1] == colors[1] &&
          combination[2] == colors[2])
        return index;
    }
    return -1;
  }

  // When fewer than three colors remain in the bank, Splendor requires
  // taking every remaining color.  Reuse the first ordinary three-color
  // policy slot containing that subset.  The missing supersets are not
  // legal in the same state, so this remains injective over legal actions
  // and matches the legacy 48-action encoder's established mapping.
  for (int index = 0; index < 10; ++index) {
    bool contains_all = true;
    for (int i = 0; i < count && contains_all; ++i) {
      bool found = false;
      for (int j = 0; j < 3; ++j)
        found = found || TAKE_DIFFERENT_COMBINATIONS[index][j] == colors[i];
      contains_all = contains_all && found;
    }
    if (contains_all)
      return index;
  }
  return -1;
}

constexpr std::array<int8_t, 32> make_take_different_index_by_mask() {
  std::array<int8_t, 32> table{};
  for (unsigned mask = 0; mask < 32; ++mask) {
    std::array<uint8_t, 5> take = {0, 0, 0, 0, 0};
    for (int color = 0; color < 5; ++color)
      take[color] = static_cast<uint8_t>((mask >> color) & 1U);
    table[mask] = static_cast<int8_t>(take_different_index_reference(take));
  }
  return table;
}

inline constexpr std::array<int8_t, 32> TAKE_DIFFERENT_INDEX_BY_MASK =
    make_take_different_index_by_mask();

struct TakeDifferentCodec {
  static constexpr const std::array<std::array<uint8_t, 3>, 10>
      &COMBINATIONS = TAKE_DIFFERENT_COMBINATIONS;

  // Hot path: every legal-action enumeration encodes each take, so the
  // colour set is mapped through a 5-bit mask table instead of a search.
  static constexpr int find_index(const std::array<uint8_t, 5> &take) {
    unsigned mask = 0;
    for (int color = 0; color < 5; ++color) {
      if (take[color] == 0)
        continue;
      if (take[color] != 1)
        return -1;
      mask |= 1U << color;
    }
    return TAKE_DIFFERENT_INDEX_BY_MASK[mask];
  }
};

constexpr bool take_different_index_matches_reference() {
  // Counts 0..2 per colour cover every control-flow path: absent colours,
  // single tokens, invalid doubles and over-long sets.
  std::array<uint8_t, 5> take = {0, 0, 0, 0, 0};
  for (int code = 0; code < 243; ++code) {
    int rest = code;
    for (int color = 0; color < 5; ++color) {
      take[color] = static_cast<uint8_t>(rest % 3);
      rest /= 3;
    }
    if (TakeDifferentCodec::find_index(take) !=
        take_different_index_reference(take))
      return false;
  }
  return true;
}

static_assert(take_different_index_matches_reference(),
              "mask-indexed take codec must match the reference search");

inline int find_visible_slot(int8_t card_id, const Board &board) {
  const auto source = csplendor::rules::find_visible_card_source(board, card_id);
  return source ? source.level * 4 + source.slot : -1;
}

inline int find_reserved_slot(int8_t card_id, const PlayerState &player) {
  return csplendor::rules::find_reserved_card_source(player, card_id);
}

template <typename Encoder, typename ScanLegalActions>
Action decode_and_match_first(int action_id, const Game &game,
                              ScanLegalActions &&scan_legal_actions) {
  Action matched;
  bool found = false;
  auto sink = [action_id, &game, &matched, &found](const Action &legal) {
    if (Encoder::encode(legal, game) != action_id)
      return true;
    matched = legal;
    found = true;
    return false;
  };
  scan_legal_actions(sink);
  return found ? matched : Encoder::decode(action_id, game);
}

constexpr bool return_codec_round_trips() {
  for (int pattern = 0; pattern < 84; ++pattern) {
    if (ReturnCodec::encode(ReturnCodec::decode(pattern)) != pattern)
      return false;
  }
  return true;
}

static_assert(return_codec_round_trips(),
              "return codec rank and unrank must be inverse operations");

} // namespace action_encoder_detail

#endif // CSPLENDOR_ACTION_ENCODER_COMMON_H
